services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolito_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: monolito_postgres
    environment:
      POSTGRES_DB: monolito_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: